# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Stefan Ott
title: Machine Learning Engineer
email: s0tt@gmx.de
website: www.github.com/s0tt/s0tt

# Dark Mode (true/false/never)
darkmode: True

# Social links
github_username:  s0tt
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: stefanott1
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Pdf Download
  icon: far fa-file-pdf
  url: https://github.com/s0tt/s0tt.github.io/raw/main/pdf/resume_ott.pdf
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Stefan and i am a Machine Learning Engineer interested in Intelligent Systems and Computer Vision.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Robert Bosch GmbH
        # link_text: boringcompany.com
        sub_title: Machine Learning Engineer - Video Perception
        caption: April 2023 - Present
        description: Machine Learning Engineer in camera video perception for automated driving.
      - layout: left
        title: Bosch Center for Artifical Intelligence
        # link_text: boringcompany.com
        sub_title: Master student research intern 
        caption: Jan 2022 - Jun 2022
        description: Research on similarity based long-tailed visual object detection.
      - layout: left
        title: Robert Bosch GmbH
        # link_text: boringcompany.com
        sub_title: Software Engineer - LiDAR base software
        caption: Oct 2018 - Sep 2020
        description: Base software development for LiDAR sensors in automated driving.     
        
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Chess
        link: github.com/s0tt/chess
        # link_text: Project Website
        additional_links:
          - title:  s0tt/chess
            icon: fab fa-github
            url: github.com/s0tt/chess
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          Project for FIDE chess implementation I started to get familiar with the game rules and the problem of search in a large solution space.
  
  # - title: Education # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: Harvard University
  #       caption: 2010 - 2013
  #       sub_title: BSc Computer Science
  #       quote: >
  #         Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
  #       description: | # this will include new lines to allow paragraphs
  #         During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

  #         I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
